// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACtPAnxpGhosCI_7qj6FsAS7mf7LsIZwE',
    appId: '1:65530689394:web:cf8247305795af00bacfeb',
    messagingSenderId: '65530689394',
    projectId: 'chainet-d67d8',
    authDomain: 'chainet-d67d8.firebaseapp.com',
    storageBucket: 'chainet-d67d8.firebasestorage.app',
    measurementId: 'G-KE5JRS4306',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-s3JdDamHcZXs9p4GegnoSOMZiTMKfE',
    appId: '1:65530689394:android:03592f7118b2e690bacfeb',
    messagingSenderId: '65530689394',
    projectId: 'chainet-d67d8',
    storageBucket: 'chainet-d67d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMWVXO6JgpTL1On6SmsOvibUZ6yQLJ7c8',
    appId: '1:65530689394:ios:361b7d9c4b1309a2bacfeb',
    messagingSenderId: '65530689394',
    projectId: 'chainet-d67d8',
    storageBucket: 'chainet-d67d8.firebasestorage.app',
    iosBundleId: 'com.example.chainet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMWVXO6JgpTL1On6SmsOvibUZ6yQLJ7c8',
    appId: '1:65530689394:ios:361b7d9c4b1309a2bacfeb',
    messagingSenderId: '65530689394',
    projectId: 'chainet-d67d8',
    storageBucket: 'chainet-d67d8.firebasestorage.app',
    iosBundleId: 'com.example.chainet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACtPAnxpGhosCI_7qj6FsAS7mf7LsIZwE',
    appId: '1:65530689394:web:f0d4203e5e2e9c16bacfeb',
    messagingSenderId: '65530689394',
    projectId: 'chainet-d67d8',
    authDomain: 'chainet-d67d8.firebaseapp.com',
    storageBucket: 'chainet-d67d8.firebasestorage.app',
    measurementId: 'G-67ZZ50T710',
  );

}